-- ================================================
-- Complete cars data from Long_EUR.xlsx
-- Total cars: 76
-- ================================================

INSERT INTO cars_long_eur (ser, car_no, type, car_group, color, model, car_case) VALUES (1, 41195, 'هونداي', 'H 1', 'فيراني', 2018, 'Rented');
INSERT INTO cars_long_eur (ser, car_no, type, car_group, color, model, car_case) VALUES (2, 44706, 'هونداي', 'H 1', 'فيراني', 2018, 'Rented');
INSERT INTO cars_long_eur (ser, car_no, type, car_group, color, model, car_case) VALUES (3, 47838, 'فورد', 'فيوجن', 'ابيض', 2019, 'Rented');
INSERT INTO cars_long_eur (ser, car_no, type, car_group, color, model, car_case) VALUES (4, 50085, 'هونداي', 'I10', 'فيراني', 2019, 'Rented');
INSERT INTO cars_long_eur (ser, car_no, type, car_group, color, model, car_case) VALUES (5, 50076, 'هونداي', 'اكسنت', 'كحلي', 2020, 'Rented');
INSERT INTO cars_long_eur (ser, car_no, type, car_group, color, model, car_case) VALUES (6, 50067, 'هونداي', 'I10', 'سلفر ميتالك', 2019, 'Rented');
INSERT INTO cars_long_eur (ser, car_no, type, car_group, color, model, car_case) VALUES (7, 50088, 'هونداي', 'النترا', 'اسود', 2020, 'Rented');
INSERT INTO cars_long_eur (ser, car_no, type, car_group, color, model, car_case) VALUES (8, 50064, 'هونداي', 'النترا', 'فيراني', 2020, 'Rented');
INSERT INTO cars_long_eur (ser, car_no, type, car_group, color, model, car_case) VALUES (9, 50058, 'هونداي', 'النترا', 'اسود', 2020, 'Rented');
INSERT INTO cars_long_eur (ser, car_no, type, car_group, color, model, car_case) VALUES (10, 50073, 'هونداي', 'النترا', 'احمر', 2020, 'Rented');
INSERT INTO cars_long_eur (ser, car_no, type, car_group, color, model, car_case) VALUES (11, 50079, 'هونداي', 'النترا', 'فيراني', 2020, 'Rented');
INSERT INTO cars_long_eur (ser, car_no, type, car_group, color, model, car_case) VALUES (12, 50061, 'هونداي', 'اكسنت', 'احمر', 2020, 'Rented');
INSERT INTO cars_long_eur (ser, car_no, type, car_group, color, model, car_case) VALUES (13, 50082, 'هونداي', 'النترا', 'احمر', 2020, 'Rented');
INSERT INTO cars_long_eur (ser, car_no, type, car_group, color, model, car_case) VALUES (14, 50952, 'فورد', 'فيوجن', 'ابيض', 2019, 'Rented');
INSERT INTO cars_long_eur (ser, car_no, type, car_group, color, model, car_case) VALUES (15, 51654, 'هونداي', 'النترا', 'سلفر ميتالك', 2020, 'Rented');
INSERT INTO cars_long_eur (ser, car_no, type, car_group, color, model, car_case) VALUES (16, 51975, 'تويوتا', 'كامري', 'فيراني', 2018, 'Rented');
INSERT INTO cars_long_eur (ser, car_no, type, car_group, color, model, car_case) VALUES (17, 42214, 'تويوتا', 'كامري', 'شمباني', 2019, 'Rented');
INSERT INTO cars_long_eur (ser, car_no, type, car_group, color, model, car_case) VALUES (18, 42703, 'هونداي', 'H1', 'ابيض', 2020, 'Rented');
INSERT INTO cars_long_eur (ser, car_no, type, car_group, color, model, car_case) VALUES (19, 51429, 'هونداي', 'H1', 'اسود', 2020, 'Rented');
INSERT INTO cars_long_eur (ser, car_no, type, car_group, color, model, car_case) VALUES (20, 54088, 'كيا', 'سيراتو', 'فيراني', 2022, 'Available');
INSERT INTO cars_long_eur (ser, car_no, type, car_group, color, model, car_case) VALUES (21, 54085, 'كيا', 'سيلتوس', 'خمري', 2022, 'Rented');
INSERT INTO cars_long_eur (ser, car_no, type, car_group, color, model, car_case) VALUES (22, 54091, 'كيا', 'سونيت', 'اسود', 2022, 'Rented');
INSERT INTO cars_long_eur (ser, car_no, type, car_group, color, model, car_case) VALUES (23, 54094, 'كيا', 'سيلتوس', 'اسود', 2022, 'Rented');
INSERT INTO cars_long_eur (ser, car_no, type, car_group, color, model, car_case) VALUES (24, 54103, 'كيا', 'بيجاس', 'فيراني', 2022, 'Rented');
INSERT INTO cars_long_eur (ser, car_no, type, car_group, color, model, car_case) VALUES (25, 54106, 'كيا', 'سيلتوس', 'خمري', 2022, 'Rented');
INSERT INTO cars_long_eur (ser, car_no, type, car_group, color, model, car_case) VALUES (26, 54109, 'خمري', 'سيلتوس', 'كيا‎', 2022, 'Rented');
INSERT INTO cars_long_eur (ser, car_no, type, car_group, color, model, car_case) VALUES (27, 54097, 'كيا', 'سونيت', 'لؤلؤي', 2022, 'Rented');
INSERT INTO cars_long_eur (ser, car_no, type, car_group, color, model, car_case) VALUES (28, 54112, 'كيا', 'سيراتو', 'فيراني', 2022, 'Rented');
INSERT INTO cars_long_eur (ser, car_no, type, car_group, color, model, car_case) VALUES (29, 54115, 'كيا', 'سونيت', 'اسود', 2022, 'Rented');
INSERT INTO cars_long_eur (ser, car_no, type, car_group, color, model, car_case) VALUES (32, 56316, 'تويوتا', 'كامري', 'فيراني ميتالك', 2023, 'Rented');
INSERT INTO cars_long_eur (ser, car_no, type, car_group, color, model, car_case) VALUES (33, 50930, 'تويوتا', 'كامري', 'فيراني ميتالك', 2023, 'Rented');
INSERT INTO cars_long_eur (ser, car_no, type, car_group, color, model, car_case) VALUES (34, 46388, 'تويوتا', 'كامري', 'سلفر ميتالك', 2023, 'Rented');
INSERT INTO cars_long_eur (ser, car_no, type, car_group, color, model, car_case) VALUES (35, 72429, 'تويوتا', 'كامري', 'سلفر ميتالك', 2023, 'Rented');
INSERT INTO cars_long_eur (ser, car_no, type, car_group, color, model, car_case) VALUES (36, 47837, 'تويوتا', 'كامري', 'سلفر ميتالك', 2023, 'Rented');
INSERT INTO cars_long_eur (ser, car_no, type, car_group, color, model, car_case) VALUES (37, 74001, 'اسود', 'كابتيفا', 'شفروليه‎', 2023, 'Rented');
INSERT INTO cars_long_eur (ser, car_no, type, car_group, color, model, car_case) VALUES (38, 54105, 'فيراني', 'كابتيفا', 'شفروليه‎', 2023, 'Rented');
INSERT INTO cars_long_eur (ser, car_no, type, car_group, color, model, car_case) VALUES (39, 46896, 'هونداي', 'H1', 'بني‎', 2019, 'Rented');
INSERT INTO cars_long_eur (ser, car_no, type, car_group, color, model, car_case) VALUES (40, 47105, 'تويوتا', 'كورو', 'سلفر ميتالك', 2023, 'Rented');
INSERT INTO cars_long_eur (ser, car_no, type, car_group, color, model, car_case) VALUES (41, 96173, 'تويوتا', 'كورو', 'بحري ميتالك', 2023, 'Rented');
INSERT INTO cars_long_eur (ser, car_no, type, car_group, color, model, car_case) VALUES (42, 53237, 'تويوتا', 'كورو', 'بحري ميتالك', 2023, 'Rented');
INSERT INTO cars_long_eur (ser, car_no, type, car_group, color, model, car_case) VALUES (44, 49898, 'تويوتا', 'كورو', 'بحري ميتالك', 2023, 'Rented');
INSERT INTO cars_long_eur (ser, car_no, type, car_group, color, model, car_case) VALUES (45, 58668, 'تويوتا', 'كورو', 'بحري ميتالك', 2023, 'Rented');
INSERT INTO cars_long_eur (ser, car_no, type, car_group, color, model, car_case) VALUES (46, 72602, 'كيا', 'بيكانتو', 'فضي', 2023, 'Rented');
INSERT INTO cars_long_eur (ser, car_no, type, car_group, color, model, car_case) VALUES (47, 52998, 'كيا', 'بيكانتو', 'اسود', 2023, 'Rented');
INSERT INTO cars_long_eur (ser, car_no, type, car_group, color, model, car_case) VALUES (48, 55721, 'كيا', 'بيكانتو', 'فضي', 2023, 'Rented');
INSERT INTO cars_long_eur (ser, car_no, type, car_group, color, model, car_case) VALUES (49, 50039, 'كيا', 'بيكانتو', 'اسود', 2023, 'Available');
INSERT INTO cars_long_eur (ser, car_no, type, car_group, color, model, car_case) VALUES (50, 49232, 'فيراني', 'سوناتا', 'هونداي‎', 2022, 'Rented');
INSERT INTO cars_long_eur (ser, car_no, type, car_group, color, model, car_case) VALUES (51, 44977, 'فيراني', 'النترا', 'هونداي‎', 2020, 'Rented');
INSERT INTO cars_long_eur (ser, car_no, type, car_group, color, model, car_case) VALUES (52, 41817, 'هونداي', 'H1', 'فيراني‎', 2018, 'Rented');
INSERT INTO cars_long_eur (ser, car_no, type, car_group, color, model, car_case) VALUES (53, 53349, 'فيراني', 'النترا', 'هونداي‎', 2025, 'Rented');
INSERT INTO cars_long_eur (ser, car_no, type, car_group, color, model, car_case) VALUES (54, 44793, 'هونداي', 'H1', 'اسود‎', 2019, 'Rented');
INSERT INTO cars_long_eur (ser, car_no, type, car_group, color, model, car_case) VALUES (55, 55270, 'سلفر', 'اﻻلنترا', 'هونداي‎', 2023, 'Rented');
INSERT INTO cars_long_eur (ser, car_no, type, car_group, color, model, car_case) VALUES (56, 53887, 'هونداي', 'سوناتا', 'كحلي', 2022, 'Rented');
INSERT INTO cars_long_eur (ser, car_no, type, car_group, color, model, car_case) VALUES (57, 53881, 'هونداي', 'سوناتا', 'احمر', 2022, 'Rented');
INSERT INTO cars_long_eur (ser, car_no, type, car_group, color, model, car_case) VALUES (58, 53890, 'هونداي', 'سوناتا', 'فيراني', 2022, 'Rented');
INSERT INTO cars_long_eur (ser, car_no, type, car_group, color, model, car_case) VALUES (59, 53765, 'اسود', 'ستاريا', 'هونداي‎', 2025, 'Rented');
INSERT INTO cars_long_eur (ser, car_no, type, car_group, color, model, car_case) VALUES (60, 48146, 'دونغ فينج', 'ايلوس شاين', 'لؤلؤي ميتالك', 2025, 'Rented');
INSERT INTO cars_long_eur (ser, car_no, type, car_group, color, model, car_case) VALUES (61, 54411, 'دونغ فينج', 'ايلوس شاين', 'لؤلؤي ميتالك', 2025, 'Rented');
INSERT INTO cars_long_eur (ser, car_no, type, car_group, color, model, car_case) VALUES (62, 51372, 'هونداي', 'H1', 'اسود‎', 2020, 'Rented');
INSERT INTO cars_long_eur (ser, car_no, type, car_group, color, model, car_case) VALUES (63, 43480, 'هونداي', 'h1', 'فيراني‎', 2020, 'Rented');
INSERT INTO cars_long_eur (ser, car_no, type, car_group, color, model, car_case) VALUES (64, 43471, 'هونداي', 'H1', 'فيراني‎', 2020, 'Rented');
INSERT INTO cars_long_eur (ser, car_no, type, car_group, color, model, car_case) VALUES (65, 43486, 'هونداي', 'H1', 'فيراني‎', 2020, 'Rented');
INSERT INTO cars_long_eur (ser, car_no, type, car_group, color, model, car_case) VALUES (66, 43465, 'هوتداي', 'H1', 'فيراني‎', 2020, 'Rented');
INSERT INTO cars_long_eur (ser, car_no, type, car_group, color, model, car_case) VALUES (67, 92933, 'هوتداي', 'سوناتا', 'خمري', 2025, 'Rented');
INSERT INTO cars_long_eur (ser, car_no, type, car_group, color, model, car_case) VALUES (68, 81324, 'هونداي', 'سوناتا', 'فيراني ميتالك', 2025, 'Rented');
INSERT INTO cars_long_eur (ser, car_no, type, car_group, color, model, car_case) VALUES (69, 53396, 'هونداي', 'سوناتا', 'فيراني', 2025, 'Rented');
INSERT INTO cars_long_eur (ser, car_no, type, car_group, color, model, car_case) VALUES (70, 99597, 'هونداي', 'سوناتا', 'كحلي', 2025, 'Rented');
INSERT INTO cars_long_eur (ser, car_no, type, car_group, color, model, car_case) VALUES (71, 96450, 'هونداي', 'سوناتا', 'خمري‎.', 2025, 'Rented');
INSERT INTO cars_long_eur (ser, car_no, type, car_group, color, model, car_case) VALUES (72, 51806, 'هونداي', 'النترا', 'ازرق', 2025, 'Rented');
INSERT INTO cars_long_eur (ser, car_no, type, car_group, color, model, car_case) VALUES (73, 54698, 'هونداي', 'i10', 'فيراني ميتالك', 2025, 'Rented');
INSERT INTO cars_long_eur (ser, car_no, type, car_group, color, model, car_case) VALUES (74, 56382, 'هونداي', 'ستاريا', 'فيراني ميتالك', 2025, 'Rented');
INSERT INTO cars_long_eur (ser, car_no, type, car_group, color, model, car_case) VALUES (75, 99913, 'هونداي', 'النترا', 'كحلي', 2025, 'Rented');
INSERT INTO cars_long_eur (ser, car_no, type, car_group, color, model, car_case) VALUES (76, 66470, 'هونداي', 'I10', 'بترولي', 2025, 'Rented');
INSERT INTO cars_long_eur (ser, car_no, type, car_group, color, model, car_case) VALUES (77, 73668, 'هونداي', 'النترا', 'فيراني ميتالك', 2025, 'Rented');
INSERT INTO cars_long_eur (ser, car_no, type, car_group, color, model, car_case) VALUES (78, 60466, 'هونداي', 'النترا', 'زيتي', 2025, 'Rented');
INSERT INTO cars_long_eur (ser, car_no, type, car_group, color, model, car_case) VALUES (79, 75083, 'هونداي', 'النترا', 'ازرق', 20256, 'Rented');
